-- Supabase/PostgreSQL schema for the Automated Timetable Generator.
-- Run this in Supabase SQL Editor to create every application table.
-- The Flask app still uses SQLAlchemy locally; this schema mirrors the models in app/models/__init__.py
-- and includes the timetable_history table used by the Supabase history sync.

create table if not exists app_user (
  id integer generated by default as identity primary key,
  name varchar(120) not null,
  email varchar(255) not null unique,
  password_hash varchar(255) not null,
  role varchar(30) not null default 'viewer' check (role in ('admin', 'scheduler', 'viewer')),
  is_active boolean not null default true,
  created_at timestamp without time zone not null default (now() at time zone 'utc')
);

create index if not exists ix_app_user_email on app_user (email);

create table if not exists lecturer (
  id integer generated by default as identity primary key,
  name varchar(120) not null,
  email varchar(255) unique
);

create table if not exists student_group (
  id integer generated by default as identity primary key,
  name varchar(120) not null unique,
  level varchar(50),
  size integer not null default 0
);

create table if not exists room (
  id integer generated by default as identity primary key,
  code varchar(50) not null unique,
  capacity integer not null,
  has_projection boolean not null default false
);

create table if not exists timeslot (
  id integer generated by default as identity primary key,
  day varchar(20) not null,
  start_time time without time zone not null default time '08:00',
  end_time time without time zone not null default time '09:00',
  label varchar(80) not null
);

create table if not exists course (
  id integer generated by default as identity primary key,
  code varchar(30) not null unique,
  title varchar(255) not null,
  expected_class_size integer not null default 0,
  weekly_contact_hours integer not null default 1,
  requires_projection boolean not null default false,
  lecturer_id integer not null references lecturer(id) on delete restrict,
  student_group_id integer not null references student_group(id) on delete restrict
);

create index if not exists ix_course_lecturer_id on course (lecturer_id);
create index if not exists ix_course_student_group_id on course (student_group_id);

create table if not exists lecturer_availability (
  id integer generated by default as identity primary key,
  lecturer_id integer not null references lecturer(id) on delete cascade,
  timeslot_id integer not null references timeslot(id) on delete cascade,
  is_available boolean not null default true,
  unique (lecturer_id, timeslot_id)
);

create index if not exists ix_lecturer_availability_lecturer_id on lecturer_availability (lecturer_id);
create index if not exists ix_lecturer_availability_timeslot_id on lecturer_availability (timeslot_id);

create table if not exists timetable (
  id integer generated by default as identity primary key,
  term varchar(120) not null default 'Current Term',
  status varchar(30) not null default 'draft',
  generated_at timestamp without time zone not null default (now() at time zone 'utc'),
  conflict_summary text default ''
);

create index if not exists ix_timetable_generated_at on timetable (generated_at desc);

create table if not exists timetable_entry (
  id integer generated by default as identity primary key,
  timetable_id integer not null references timetable(id) on delete cascade,
  course_id integer not null references course(id) on delete restrict,
  lecturer_id integer not null references lecturer(id) on delete restrict,
  room_id integer not null references room(id) on delete restrict,
  timeslot_id integer not null references timeslot(id) on delete restrict,
  student_group_id integer not null references student_group(id) on delete restrict
);

create index if not exists ix_timetable_entry_timetable_id on timetable_entry (timetable_id);
create index if not exists ix_timetable_entry_course_id on timetable_entry (course_id);
create index if not exists ix_timetable_entry_lecturer_id on timetable_entry (lecturer_id);
create index if not exists ix_timetable_entry_room_id on timetable_entry (room_id);
create index if not exists ix_timetable_entry_timeslot_id on timetable_entry (timeslot_id);
create index if not exists ix_timetable_entry_student_group_id on timetable_entry (student_group_id);

create table if not exists timetable_history (
  id bigint generated by default as identity primary key,
  local_id integer,
  term text not null,
  status text not null,
  generated_at timestamptz not null,
  conflict_summary text default '',
  entries jsonb not null default '[]'::jsonb,
  inserted_at timestamptz not null default now()
);

create index if not exists ix_timetable_history_generated_at on timetable_history (generated_at desc);
